#! /bin/bash
# Verify that a  specificed program is either valid as is or can be found in the PATH directory list

in_path() {
  cmd=$1
  paths=$2
  IFS=":"
  result=1
  
  for dir in $paths; do
    if [[ -x $dir/$cmd ]] ; then
      result=0
    fi
  done

  return $result
}

check_cmd_in_path() {
  var=$1
  if [[ $var != "" ]] ; then
    if [[ ${var:0:1} = "/" ]] ; then
      if [[ ! -x $var ]] ; then
        return 1
      fi
    elif ! in_path $var $PATH ; then
      return 2
    fi
  fi
}

if [[ $# -ne 1 ]]; then
  echo "bad usage"; exit 1
fi

check_cmd_in_path $1
case $? in 
  0 ) echo "found";;
  1 ) echo "not found or not executable";;
  2 ) echo "not found in \$PATH";;
esac

exit 0